### ISSUE TITLE
I type the code then it says "password:". With a keychain symbol after the colon.

### ISSUE THREAD

**Issue by Bombo7544** [octomagon/davegrohl#23]
![screen shot 2017-05-08 at 9 40 25 pm](https://cloud.githubusercontent.com/assets/28553445/25834708/fbe4922a-3436-11e7-8699-e35cf059c90a.png)
This is version 3 btw

**Comment by Bombo7544** [comment]
HELP ME!!

**Comment by dead-null** [comment]
have you not ever used a *nix system? sudo will ask for your password if your sudoers requires passwords for running binaries as a privileged user. Type the sudoers password. If you don't know what this is you should learn that before you learn dave. It will help in the long run.

**Comment by Bombo7544** [comment]
I dont know what nix system is. I dont know what privileged user is. I dont know what running binaries are. I dont know what a sudoer is.

**Comment by Bombo7544** [comment]
Also how do you find the sudoers password

**Comment by dead-null** [comment]
Great. Research those things you said you don't know and your answer follows. A great resource to get you started is 'www.google.com'.

**Comment by octomagon** [comment]
Jack,
What are you trying to use Dave for?  If you're locked out of a Mac, there are much easier ways to get back in.  Password Crackers are generally not very useful in the real world.  Dave was written more as a fun experiment rather than a practical tool.  If you're just having fun or trying to learn, more power to you!  Please be careful however, as running Dave for long periods of time can easily overheat or damage a computer.
