### ISSUE TITLE
Couldn't find the correct hashing function.

### ISSUE THREAD

**Issue by ghost** [octomagon/davegrohl#28]

**Comment by octomagon** [comment]
A couple of questions:

- Can you show the full terminal session when have to repeatedly try 3-4 times?
- What do you see when you try to run the binary copied by `make install`?
- What does Dave output when you run `sudo ./dave -s YourUsername`? (remember to scramble the hex output before posting).

To troubleshoot, you may want to create a new user on your Mac with a bad password like "apple".  Try to run Dave on that user and see if the problem persists.  That'll tell you if the issue is specific to your user.  

Dave should not act differently when run repeatedly.  Does the issue persist if you recompile Dave by running `make clean && make`.  If some of the .o files were created at different times, that would explain the erratic behavior.  I have no clue why `make install` should break the binary.  It's location should not make a difference.  This unpredictability smells like dangling pointers to me...
