### ISSUE TITLE
How to run this app?

### ISSUE THREAD

**Issue by amoc1000** [octomagon/davegrohl#7]
Hi,

I try the command:

sudo /.dave -u the_username

The terminal gave me

sudo: ./dave: command not found

**Comment by octomagon** [comment]
Hi!
Make sure dave is in your current working directory.  You can see if it is by typing 'ls -lh'.  If you cloned the git repo and compiled it with 'make',  dave will be created in the bin directory then you can 'cd bin' and your command will work

**Comment by octomagon** [comment]
I'll update the readme later today with more details.

**Comment by octomagon** [comment]
The README has a brief tutorial now.  Dave also compiles into the base directory instead of 'bin'.  I think it's a bit more user-friendly this way.  This also make to overall project structure a little simpler since dave looks for the 'wordlists' folder in the same directory dave is in.  Putting 'wordlists' in 'bin' seems sloppy.
